language: python

python:
  - "3.10"
  - "3.11"

env:
  global:
    - secure: K6dO7Mksu4WVMi8HUboI7zTdOOTlRiEhVNNDdajiSzypAXjliCckQedupiB0rIDQuLnT1bZjCozGFVlm0HOVpd+jEEVCBgUufA6vJK/xvt2fgNzONWJzWysEV2wL98wGt8SILLXI2l7auG0Y5EU/Txi4hawVo8dSicco0WKVBzyNrtEZQTMUQ6IpwNd/MVMkwsu64v+R8l6lsCJshHIO1mHwJOUGI2S33s51Egvv085tMyk1fmbjUGI1hnreqTVsS/+hMQ3uNuL6oN2ncO8wdRgjiJHBeXhNz6zW1uxJKQZb1vbPorV+SkLgLGREd58KJU9K0TKrt4LYlSUs8eXng94lwsMig3jRYwuuFMEYiy+QTS/tfBAyEnaw4hmR5q4ZTZD2hLCiZ8oQE/LWEtlFEqabLKNRJQfo/ogWw/p+e71NWXqafnwMYeIjYkhIwdkooOA14GBB5IjSURP41Q5wLqf0oSmDqnWKm5JzhvQ+ni0Cb2oGLj90DipWQfOLz+ChdU8XH/O2NpQf27GuILxxx2JMq+T1AbpjX23c+9Qdn0cmqoLXUdQpgLHL6lQyOgLJhquzX8VbxvQmSaGwmnPA9skfFOIP/WWscnN5jaTu84RHfxwh/9uT3GHnJ9eROe1RmmzzYYN9eK247jdjISa7nCBDn/rpNvF0NNXrA+M2hhg=

before_install:
  - pip install numpy h5netcdf pytest pytest-cov codecov
  # build doc only on Python 3.8
  # XXX: Klink does not exist for Python 3 but we also don't need to update the docs right now
  # as nothing in quite some time.
  # Let's deal with it as we hit it.
  # - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install sphinx klink ; fi

install:
  - git version
  - git fetch origin --tags
  - git remote add pyexodus git://github.com/SalvusHub/pyexodus.git
  - git fetch pyexodus --tags
  - git status
  - pip install -v -e .
  - git status

script:
  - py.test --cov=pyexodus
  # Docs only need to be built once.
  # XXX: Reenable to rebuild docs.
  # - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then cd $TRAVIS_BUILD_DIR/doc; make html ; fi

after_success:
  - cd $TRAVIS_BUILD_DIR; codecov
  # XXX: Reenable to rebuild docs.
  # - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; fi
