#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
:copyright:
    Lion Krischer (lionkrischer@gmail.com), 2016
:license:
    MIT License
"""
import os

import h5netcdf
import numpy as np

from pyexodus import exodus


def test_initialization(tmpdir):
    filename = os.path.join(tmpdir.strpath, "example.e")

    e = exodus(filename,
               mode="w",
               title="Example",
               array_type="numpy",
               numDims=3,
               numNodes=5,
               numElems=6,
               numBlocks=1,
               numNodeSets=0,
               numSideSets=1)
    e.close()

    # Just manually test everything.
    with h5netcdf.File(filename, mode="r") as f:
        """
        Tests initialization.

        Test data has been generated by using the official exodus Python API.
        """
        assert dict(f.attrs) == {
            'api_version': np.array([6.30000019], dtype=np.float32),
            'file_size': np.array([1], dtype=np.int32),
            'floating_point_word_size': np.array([8], dtype=np.int32),
            'int64_status': np.array([0], dtype=np.int32),
            'maximum_name_length': np.array([32], dtype=np.int32),
            'title': 'Example',
            'version': np.array([6.30000019], dtype=np.float32)}

        assert dict(f.dimensions) == {
            'four': 4,
            'len_line': 81,
            'len_name': 33,
            'len_string': 33,
            'num_dim': 3,
            'num_el_blk': 1,
            'num_elem': 6,
            'num_nodes': 5,
            'num_side_sets': 1,
            'time_step': 0}

        assert list(f.groups) == []

        # Testing the variables is a bit more effort.

        # Generate with
        # v = f.variables
        # {k: {"dimensions": v[k].dimensions,
        #      "shape": v[k].shape,
        #      "dtype": v[k].dtype,
        #      "attrs": dict(v[k].attrs),
        #      "data": v[k][:]} for k in f.variables.keys()} == \

        expected = {
            'coor_names': {
                'attrs': {},
                'data': np.array([
                    ['', '', '', '', '', '', '', '', '', '', '', '', '', '',
                     '', '', '', '', '', '', '', '', '', '', '', '', '', '',
                     '', '', '', '', ''],
                    ['', '', '', '', '', '', '', '', '', '', '', '', '', '',
                     '', '', '', '', '', '', '', '', '', '', '', '', '', '',
                     '', '', '', '', ''],
                    ['', '', '', '', '', '', '', '', '', '', '', '', '', '',
                     '', '', '', '', '', '', '', '', '', '', '', '', '', '',
                     '', '', '', '', '']], dtype='|S1'),
                'dimensions': ('num_dim', 'len_name'),
                'dtype': np.dtype('S1'),
                'shape': (3, 33)},
            'coordx': {'attrs': {},
                       'data': np.array([0., 0., 0., 0., 0.]),
                       'dimensions': ('num_nodes',),
                       'dtype': np.dtype('float64'),
                       'shape': (5,)},
            'coordy': {'attrs': {},
                       'data': np.array([0., 0., 0., 0., 0.]),
                       'dimensions': ('num_nodes',),
                       'dtype': np.dtype('float64'),
                       'shape': (5,)},
            'coordz': {'attrs': {},
                       'data': np.array([0., 0., 0., 0., 0.]),
                       'dimensions': ('num_nodes',),
                       'dtype': np.dtype('float64'),
                       'shape': (5,)},
            'eb_names': {'attrs': {},
                         'data': np.array([
                             ['', '', '', '', '', '', '', '', '', '', '',
                              '', '', '', '', '', '', '', '', '', '', '',
                              '', '', '', '', '', '', '', '', '', '', '']],
                             dtype='|S1'),
                         'dimensions': ('num_el_blk', 'len_name'),
                         'dtype': np.dtype('S1'),
                         'shape': (1, 33)},
            'eb_prop1': {'attrs': {'name': 'ID'},
                         'data': np.array([-1], dtype=np.int32),
                         'dimensions': ('num_el_blk',),
                         'dtype': np.dtype('int32'),
                         'shape': (1,)},
            'eb_status': {'attrs': {},
                          'data': np.array([0], dtype=np.int32),
                          'dimensions': ('num_el_blk',),
                          'dtype': np.dtype('int32'),
                          'shape': (1,)},
            'ss_names': {'attrs': {},
                         'data': np.array([
                             ['', '', '', '', '', '', '', '', '', '', '',
                              '', '', '', '', '', '', '', '', '', '', '',
                              '', '', '', '', '', '', '', '', '', '', '']],
                             dtype='|S1'),
                         'dimensions': ('num_side_sets', 'len_name'),
                         'dtype': np.dtype('S1'),
                         'shape': (1, 33)},
            'ss_prop1': {'attrs': {'name': 'ID'},
                         'data': np.array([-1], dtype=np.int32),
                         'dimensions': ('num_side_sets',),
                         'dtype': np.dtype('int32'),
                         'shape': (1,)},
            'ss_status': {'attrs': {},
                          'data': np.array([0], dtype=np.int32),
                          'dimensions': ('num_side_sets',),
                          'dtype': np.dtype('int32'),
                          'shape': (1,)},
            'time_whole': {'attrs': {},
                           'data': np.array([], dtype=np.float64),
                           'dimensions': ('time_step',),
                           'dtype': np.dtype('float64'),
                           'shape': (0,)}}

        for key in sorted(expected.keys()):
            a = f.variables[key]
            e = expected[key]

            assert dict(a.attrs) == e["attrs"], key
            np.testing.assert_equal(a[:], e["data"], err_msg=key)
            assert a.dimensions == e["dimensions"], key
            assert a.dtype == e["dtype"], key
            assert a.shape == e["shape"], key
